CREATE TABLE IF NOT EXISTS `BAPIKEYS` (
  `BID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BOWNERID` bigint(20) NOT NULL DEFAULT 0,
  `BNAME` varchar(96) NOT NULL DEFAULT '',
  `BKEY` varchar(128) NOT NULL DEFAULT '',
  `BSTATUS` varchar(16) NOT NULL DEFAULT 'active',
  `BCREATED` int(11) NOT NULL DEFAULT 0,
  `BLASTUSED` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`BID`),
  KEY `BOWNERID` (`BOWNERID`),
  KEY `BSTATUS` (`BSTATUS`),
  KEY `BKEY` (`BKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 